# Based on https://github.com/rp-rs/rp-hal/blob/c8bb2e43c792dd3975a255d7eba479547411aec6/.github/workflows/rustfmt.yml
on: [push, pull_request]
name: Code formatting check
jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-20.04
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv6m-none-eabi
          override: true
          profile: minimal
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
